version: '3'
services:
  app:
    build: "."
    volumes:
      - "./app:/app"
    working_dir: "/app"
    command: "wasm-pack build"
  demo:
    image: "node:16.19.0-bullseye-slim"
    volumes:
      - "./app:/app"
      - "./demo:/demo"
    working_dir: "/demo"
    user: "node"
    command: "sh -c 'npm i && npm run dev'"
    ports:
      - "8080:8080"
